apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: content-creator
    image: alicek106/alpint-wget:latest
    args: [ "tail", "-f", "/dev/null" ]
    volumeMounts:
      - mountPath: /data
        name: my-emptydir-volume

  - name: apache-webserver
    image: httpd:2
    volumeMounts:
      - mountPath: /usr/local/apache2/htdocs/
        name: my-emptydir-volume

  volumes:
    - name: my-emptydir-volume
      emptyDir: {}
