apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: nfs-mount-container
    image: busybox
    args: [ "tail", "-f", "/dev/null" ]
    volumeMounts:
      - mountPath: /mnt
        name: nfs-volume
  volumes:
  - name: nfs-volume
    nfs:
      path: /
      server: 10.187.63.43
