apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-dynamic-provisioning
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: 'nfs-client'