apiVersion: v1
kind: Pod
metadata:
  name: completed-pod-restart-never
spec:
  restartPolicy: Never
  containers:
  - name: completed-pod-restart-never
    image: busybox
    # 종료 코드를 1로 반환(0이 아닌 종료코드)하도록 설정
    # 종료 코드가 1이 반환되므로 파드의 상태가 Error로 출력되고 유지된다(restartPolicy: Never)
    command: ["sh"]
    args: ["-c", "sleep 10 && exit 1"]