# 다음은 다른 서비스 또는 디플로이먼트가 생성될 때까지 Init 컨테이너에서 대기하는 예시이다
# 쿠버네티스에서는 여러 리소스를 한 번에 생성할 때 각 리소스의 의존성을 정의하는 기능을 별도로 제공하지는 않지만, Init 컨테이너를 제공하면 아래와 같이 간접적으로 의존성을 정의할 수 있다
apiVersion: v1
kind: Pod
metadata:
  name: init-container-usecase
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
    - name: wait-other-service
      image: busybox
      command: ["sh", "-c", 'until nslookup mywebservice; do echo waiting..; sleep 1; done;']

