apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffintity-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mylabel/disk
            operator: In
            values:
            - ssd
            - hdd
  containers:
  - name: nginx
    image: nginx:latest