apiVersion: v1
kind: Pod
metadata:
  name: nginx-podaffintity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: mylabel/database
            operator: In
            values:
            - mysql
        topologyKey: failure-admin.beta.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:latest