apiVersion: v1
kind: Pod
metadata:
  name: poststart-hook
spec:
  containers:
  - name: poststart-hook
    image: nginx
    # 컨테이너가 실행됨과 동시에 /myfile이 생성된다
    # postStart는 컨테이너의 Entrypoint와는 비동기적으로 실행되며, 어떠한 것이 먼저 실행된다는 보장은 없다
    # postStart의 명령어나 HTTP 요청이 제대로 실행되지 않으면 컨테이너는 Running 상태로 전환되지 않으며, Init 컨테이너와 마찬가지로 restartPolicy에 의해 해당 컨테이너가 재시작 된다
    # postStart 단계에서 시간이 오래 걸리면 그만큼 Running 상태에 도달하는 시간이 길어질 수 있다
    # Init 컨테이너의 로그는 kubectl logs <파드 이름> -c <컨테이너 이름>으로 확인할 수 있지만, postStart에 의한 실행 로그는 에러가 발생하지 않는 한 별도로 확인할 수 없다
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "touch /myfile"]

