apiVersion: v1
kind: Pod
metadata:
  name: readinessprobe-pod
  labels:
    my-readinessprobe: test
spec:
  containers:
  - name: readinessprobe-pod
    image: nginx
    readinessProbe:     # <파드 IP>:80/ 로 상태 검사 요청을 전송한다
      httpGet:
        port: 80
        path: /

---

apiVersion: v1
kind: Service
metadata:
  name: readinessprobe-svc
spec:
  selector:
    my-readinessprobe: test
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  type: ClusterIP

