version: '3.0'
services:
  my_container_1:
    image: alicek106/composetest:mysql
  my_container_2:
    image: alicek106/composetest:mysql
  web:
    links:
      - db
      - db:database
      - redis
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE_NAME=mydb
    command: apachectl -DFOREGROUND
    # command: [apachectl, -DFOREGROUND]
    depends_on:
      - mysql
    entrypoint: ./sync_script.sh mysql:3306
    ports:
      - "8080"
      - "8081-8085"
      - "80:80"
    build: ./composetest
    context: ./composetest
    dockerfile: myDockerfile
    args:
      HOST_NAME: web
      HOST_CONFIG: self_config
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: overlay
    driver_opts:
      subnet: "255.255.255.0"
      IPAdress: "10.0.0.2"