apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-volume
spec:
  serviceName: statefulset-volume-service
  selector:
    matchLabels:
      name: statefulset-volume-example
  replicas: 3
  template:
    metadata:
      labels:
        name: statefulset-volume-example
    spec:
      containers:
      - name: statefulset-volume-example
        image: alicek106/rr-test:echo-hostname
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: webserver-files
          mountPath: /var/www/html/
  volumeClaimTemplates:
  - metadata:
      name: webserver-files
    spec:
      accessModes: ["ReadWriteOnce"]
      # ncs-csi 라는 스토리지 클래스와 NFS 프로비저너를 미리 생성해 두었다
      storageClassName: nfs-csi
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: statefulset-volume-service
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    name: statefulset-volume-example