apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-rolebinding
subjects:
- kind: Group
  name: system:serviceaccounts
roleRef:
  apiGroup: ClusterRole
  kind: service-reader
  name: rbac.authorization.k8s.io