apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding-user
  namespace: default
subjects:
- kind: User
  name: pjw-crt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-reader