apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployments-ns
  namespace: production
spec:
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: test-nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
spec:
  selector:
    app: test-deploy
  ports:
  - port: 8010
    targetPort: 80

