apiVersion: v1
kind: Pod
metadata:
  name: secret-env-example
spec:
  containers:
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    volumeMounts:
      - mountPath: /etc/secret
        name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: our-password
      items:
        - key: pw1
          path: password1