apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-lb-local
spec:
  externalTrafficPolicy: Local
  selector:
    app: webserver
  ports:
  - name: web-port
    port: 80
    targetPort: 80
  type: LoadBalancer
